### ISSUE TITLE
rna_container_id in JgiMtInterface is still accepting strings > 20 charcters

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#112]
`sheets_and_friends/tsv_in/validation_converter.tsv` has the following line
{text < 20 characters},linkml string_serialization,DH pattern regex,"^.{1,20}$",9

That configuration is used in this target:

```make
local/with_modifications.yaml: local/with_shuttles_yq.yaml \
sheets_and_friends/tsv_in/modifications_long.tsv \
sheets_and_friends/tsv_in/validation_converter.tsv \
local/nmdc.yaml
	$(RUN) modifications_and_validation \
		--yaml_input $< \
		--modifications_config_tsv $(word 2,$^) \
		--validation_config_tsv $(word 3,$^) \
		--yaml_output $@.raw
```

I think @pkalita-lbl made a PR in which erroneous `from_type` values of "NMDC string serialization" were changed to "linkml string_serialization"

see 
- https://github.com/microbiomedata/submission-schema/pull/101
- https://github.com/microbiomedata/sheets_and_friends/blob/6b4dcfccbd9b02b306667ec5435aee13b1627359/sheets_and_friends/modifications_and_validation.py#L224
- https://github.com/microbiomedata/submission-schema/pull/101/commits/e4c8af0c580d9ebff7741105cdb948b441a186a6#diff-662075e86a323ec3244e627157411c9456005fd0ee32317931e87202777ea0c3

**Comment by turbomam** [comment]
https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/portal/jgi_metatranscriptomics.yaml

```yaml
  rna_container_id:
    title: RNA container label
    comments:
      - Must be unique across all tubes and plates, and <20 characters. All samples
        in a plate should have the same plate label.
    examples:
      - value: Pond_MT_041618
    from_schema: https://example.com/nmdc_dh
    rank: 9
    #    string_serialization: '{text}'
    string_serialization: '{text < 20 characters}'
    slot_group: JGI-Metatranscriptomics
    recommended: true
```

**Comment by turbomam** [comment]
main is currently https://github.com/microbiomedata/nmdc-schema/commit/e8f9bbdf7273dcfd440067067c61cecc5d8a86d9

**Comment by turbomam** [comment]
sheets_and_friends/tsv_in/import_slots_regardless.tsv is using source file or URL values of 
https://raw.githubusercontent.com/microbiomedata/nmdc-schema/e8f9bbdf7273dcfd440067067c61cecc5d8a86d9/nmdc_schema/nmdc_materialized_patterns.yaml

**Comment by turbomam** [comment]
`sheets_and_friends/tsv_in/import_slots_regardless.tsv` has the following in `source file or URL`

https://raw.githubusercontent.com/microbiomedata/nmdc-schema/e8f9bbd/nmdc_schema/nmdc_materialized_patterns.yaml

are we sure that that file contains a string_serialization: '{text < 20 characters}' for rna_container_id ?

**Comment by turbomam** [comment]
No, https://raw.githubusercontent.com/microbiomedata/nmdc-schema/e8f9bbd/nmdc_schema/nmdc_materialized_patterns.yaml has the following so needs to be regenreated

```yaml
  rna_container_id:
    name: rna_container_id
    title: RNA container label
    comments:
    - Must be unique across all tubes and plates, and <20 characters. All samples
      in a plate should have the same plate label.
    examples:
    - value: Pond_MT_041618
    from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
    rank: 9
    string_serialization: '{text}'
    slot_group: JGI-Metatranscriptomics
    recommended: true
```
