### ISSUE TITLE
Align `rna_volume` validation constraints with comments

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#116]
slot_usage for `JgiMtInterface`

```yaml
rna_volume:
  name: rna_volume
  title: RNA volume in ul
  comments:
    - Units must be in uL. Enter the numerical part only. Value must 0-1000. Values <25 by special permission only.
  examples:
    - value: '25'
  from_schema: https://raw.githubusercontent.com/microbiomedata/nmdc-schema/main/src/schema/nmdc
  rank: 6
  string_serialization: '{float}'
  owner: Biosample
  domain_of:
    - Biosample
  slot_group: jgi_metatranscriptomics_section
  range: float
  required: true
  recommended: true
```

Needs `minimum_value` and `maximum_value` specifications.

Should the minimum be 0 or 25?

A good way to check this sort of thing by generating local/usage_template.tsv with the project.Makefile. I see that there are no slots with a `minimum_value` set to anything higher than 0. @mslarae13 what behavior do you want here? We should make sure that the comment and the validation rules are harmonious. Maybe we need to say more about what "special permission" is and who to get it from.

_Typo? Value must 0-1000_

cc @brynnz22 @mslarae13
