### ISSUE TITLE
analysis_type is both required and recommended for class WaterInterface

### ISSUE THREAD

**Issue by aclum** [microbiomedata/submission-schema#171]
See https://microbiomedata.github.io/submission-schema/WaterInterface/ 
If I look at the linkml source for slot analysis_type for this class has both required and recommended are both set to true.
 analysis_type:
    name: analysis_type
    description: Select all the data types associated or available for this biosample
    title: analysis/data type
    examples:
    - value: metagenomics; metabolomics; proteomics
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - MIxS:investigation_type
    rank: 3
    multivalued: true
    alias: analysis_type
    owner: WaterInterface
    domain_of:
    - Biosample
    - DhMultiviewCommonColumnsMixin
    slot_group: sample_id_section
    range: analysis_type_enum
    **required: true
    recommended: true**

**Comment by bmeluch** [comment]
`analysis_type` is "recommended" in the [NMDC schema definition](https://microbiomedata.github.io/nmdc-schema/analysis_type/) 

Then, in the submission schema, [modifications_long.tsv](https://github.com/microbiomedata/submission-schema/blob/main/sheets_and_friends/tsv_in/modifications_long.tsv) updates it to "required" for all interface classes that use `DhMultiviewCommonColumnsMixin` (which is all the interfaces)

Except instead of replacing "recommended" with "required", both stick around.

As another example, the same thing is happening with `dna_concentration` in `JgiMgInterface`. `dna_concentration` is "recommended" in the [NMDC schema definition](https://microbiomedata.github.io/nmdc-schema/dna_concentration/), and then updated to be "required" in [modifications_long.tsv](https://github.com/microbiomedata/submission-schema/blob/main/sheets_and_friends/tsv_in/modifications_long.tsv). The result in the submission schema LinkML source is this:

```
  dna_concentration:
    name: dna_concentration
    title: DNA concentration in ng/ul
    comments:
    - Units must be in ng/uL. Enter the numerical part only. Must be calculated using
      a fluorometric method. Acceptable values are 0-2000.
    examples:
    - value: '100'
    from_schema: https://w3id.org/nmdc/nmdc
    see_also:
    - nmdc:nucleic_acid_concentration
    rank: 5
    owner: Biosample
    domain_of:
    - Biosample
    - ProcessedSample
    - JgiMgInterface
    slot_group: jgi_metagenomics_section
    range: float
    required: true
    recommended: true
    minimum_value: 0
    maximum_value: 2000
```

tl;dr I don't know how to fix this but it's happening in a bunch of places in addition to WaterInterface
