### ISSUE TITLE
makefile cleanup: identify out-dated code; extract todos into issues

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#253]
remove  some of these scripts?

```toml
oak-tree-to-pv-list = "nmdc_submission_schema.scripts.oak_tree_to_pv_list:main"
dh-json2linkml = 'nmdc_submission_schema.scripts.dh_json2linkml:update_json'
linkml-json2dh = 'nmdc_submission_schema.scripts.linkml_json2dh:extract_lists'
```

- use fewer enums? is that really desirable or even possible?
- use booleans for yes/no enumerations? what would the benefit be?
- check for numbers that appear as strings in the schema (just examples? check for minimum value etc)
- check if maximum value for pH has to be an int?
- RDF/TTL generation is failing https://github.com/microbiomedata/submission-schema/issues/13

## old hints for alternate import sources in `pyproject.toml`:

- /Users/MAM/Documents/gitrepos/sheets_and_friends
- home/mark/gitrepos/sheets_and_friends
- sheets-and-friends = { path = "/home/mark/gitrepos/sheets_and_friends", develop = true }
