### ISSUE TITLE
Check NMDC-wide parity between soil Biosample capture, validation and serialization 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#32]
The availability of the resource links mentioned in this issue may be limited to NMDC team members or even just Data Portal admins.

- I visited https://data.microbiomedata.org/ (the production version of NMDC's Data Portal) and logged in my ORCID.
- Then I clicked the button for the Submission Portal, which took me to https://data.microbiomedata.org/submission/home.
- I entered two soil Biosamples, with no EMSL or JGI information: https://data.microbiomedata.org/submission/02a0cab2-3ff3-4663-a5e0-09a1a14a3f48/samples. Then I clicked the `DOWNLOAD XLSX` button and renamed the resulting file as [02a0cab2-3ff3-4663-a5e0-09a1a14a3f48.xlsx](https://github.com/microbiomedata/submission-schema/files/10992992/02a0cab2-3ff3-4663-a5e0-09a1a14a3f48.xlsx)
- I couldn't figure out the acceptable format for the following columns, so I left them blank:
  - `history/agrochemical additions`
  - `extreme_unusual_properties/Al saturation`
  - `extreme_unusual_properties/heavy metals`
  - `miscellaneous parameter`
- note that in the XLSX output format, columns that are allowed to take multivalued responses are pated together with `; `, like 'metagenomics; metatranscriptomics' for `analysis/data type`. Another column following this pattern is `history/tillage`. The submission portal doesn't seem to provide a user control for exporting in any format other than XLSX. **I will also try fetching from the Submission Portal API.**
- There are other cells that require semicolons (`;`) as part of a validation pattern, like `light regimen` with a legal but poorly typed value of 'ncandescant light;10 lux;450 nanometer;. This confusion of semicolons for separating multiple values and for formatting compound values is not ideal.
- Also note that I am mentioning columns, as they appear in the Submission Portal and in the XLSX output, by their LinkML `title`s. This works well for loading data back into the Data Portal, but is not ideal for converting into LinkML JSON or YAML. In those cases, identifying columns with LinkML `name`s is required (?)

**Comment by turbomam** [comment]
The submission an be retrieved from https://data.microbiomedata.org/api/docs#/metadata_submission/get_submission_api_metadata_submission__id__get by persons or agents with the necessary authorization. (Submission Portal administrators? All logged-in users?)

The following URL will work from browsers where an authorized user is logged in: 
https://data.microbiomedata.org/api/metadata_submission/02a0cab2-3ff3-4663-a5e0-09a1a14a3f48

Accessing that content with `curl` or in a program is more complex. It currently requires manually retrieving `https://data.microbiomedata.org`'s `session` cookie and including that in the request. _(Elaborate?)_

The submissions are stored in a Postgres database. Some of the structured content is bundled together in one BSON object. _(Provide whatever schema there is for the payload?)_

**Comment by turbomam** [comment]
The full content from https://data.microbiomedata.org/api/metadata_submission/02a0cab2-3ff3-4663-a5e0-09a1a14a3f48 is provided below:


```json
{
  "metadata_submission": {
    "packageName": "soil",
    "contextForm": {
      "datasetDoi": "",
      "dataGenerated": true,
      "facilityGenerated": null,
      "facilities": [],
      "award": null,
      "otherAward": ""
    },
    "addressForm": {
      "shipper": {
        "name": "",
        "email": "",
        "phone": "",
        "line1": "",
        "line2": "",
        "city": "",
        "state": "",
        "postalCode": ""
      },
      "expectedShippingDate": null,
      "shippingConditions": "",
      "sample": "",
      "description": "",
      "experimentalGoals": "",
      "randomization": "",
      "usdaRegulated": null,
      "permitNumber": "",
      "biosafetyLevel": "",
      "irbOrHipaa": null,
      "comments": ""
    },
    "templates": [
      "soil"
    ],
    "studyForm": {
      "studyName": "this is a genuinely long study name",
      "piName": "",
      "piEmail": "mam@lbl.gov",
      "piOrcid": "",
      "linkOutWebpage": [],
      "studyDate": null,
      "description": "",
      "notes": "",
      "contributors": []
    },
    "multiOmicsForm": {
      "alternativeNames": [],
      "studyNumber": "",
      "GOLDStudyId": "",
      "JGIStudyId": "",
      "NCBIBioProjectId": "",
      "omicsProcessingTypes": []
    },
    "sampleData": {
      "soil_data": [
        {
          "ph": "9",
          "alt": "111 units",
          "elev": "123 m",
          "fire": "xxx",
          "temp": "111 units",
          "depth": "111",
          "lat_lon": "77 88",
          "ph_meth": "xxx",
          "sieving": "xxx",
          "tillage": [
            "drill",
            "chisel"
          ],
          "flooding": "xxx",
          "salinity": "111 units",
          "tot_carb": "111 units",
          "ecosystem": "Environmental",
          "fao_class": "Rankers",
          "org_nitro": "111 units",
          "phosphate": "111 units",
          "samp_name": "a",
          "samp_size": "111 units",
          "soil_type": "xxx [ENVO:00000000]",
          "tot_phosp": "111 units",
          "env_medium": "bare soil [ENVO:01001616]",
          "light_regm": "ncandescant light;10 lux;450 nanometer",
          "org_matter": "111 units",
          "store_cond": "frozen",
          "al_sat_meth": "xxx",
          "annual_temp": "111 units",
          "biotic_regm": "xxx",
          "env_package": "soil",
          "local_class": "xxx",
          "sample_link": "z:99",
          "season_temp": "111 units",
          "cur_land_use": "cities",
          "geo_loc_name": "USA: Maryland, Bethesda",
          "growth_facil": "greenhouse",
          "horizon_meth": "xxx",
          "size_frac_up": "111 units",
          "slope_aspect": "100 units",
          "soil_horizon": "O horizon",
          "tot_org_carb": "111 units",
          "air_temp_regm": [
            "xxx"
          ],
          "analysis_type": [
            "metagenomics"
          ],
          "annual_precpt": "111 units",
          "crop_rotation": "xxx",
          "extreme_event": "xxx",
          "filter_method": "xxx",
          "humidity_regm": [
            "xxx"
          ],
          "oxy_stat_samp": "aerobic",
          "rel_to_oxygen": "aerobe",
          "salinity_meth": "xxx",
          "season_precpt": "111 units",
          "size_frac_low": "99 units",
          "source_mat_id": "x:1",
          "water_content": "111 units",
          "watering_regm": [
            "xxx"
          ],
          "cur_vegetation": "xxx",
          "drainage_class": "well",
          "ecosystem_type": "Soil",
          "slope_gradient": "111 units",
          "soil_type_meth": "xxx",
          "start_date_inc": "2022-02-15",
          "start_time_inc": "13:33:55",
          "tot_org_c_meth": "xxx",
          "collection_date": "2022-01-15",
          "collection_time": "11:11",
          "env_broad_scale": "urban biome [ENVO:01000249]",
          "env_local_scale": "__tunnel [ENVO:00000068]",
          "link_class_info": "xxx",
          "other_treatment": "xxx",
          "samp_store_temp": "-80 Celsius",
          "carb_nitro_ratio": "0.5",
          "isotope_exposure": "xxx",
          "local_class_meth": "xxx",
          "org_nitro_method": "xxx",
          "profile_position": "summit",
          "samp_mat_process": "xxx",
          "ecosystem_subtype": "Unclassified",
          "heavy_metals_meth": "xxx",
          "link_climate_info": "xxx",
          "microbial_biomass": "111 units",
          "previous_land_use": "circus tent;+0530",
          "soil_text_measure": "111 units",
          "soil_texture_meth": "xxx",
          "tot_nitro_content": "111 units",
          "ecosystem_category": "Terrestrial",
          "micro_biomass_meth": "xxx",
          "non_microb_biomass": "111 units",
          "prev_land_use_meth": "xxx",
          "samp_collec_device": "xxx",
          "samp_collec_method": "xxx",
          "specific_ecosystem": "Unclassified",
          "biotic_relationship": "free living",
          "chem_administration": [
            "xxx"
          ],
          "climate_environment": [
            "xxx"
          ],
          "collection_date_inc": "2022-01-22",
          "collection_time_inc": "11:11",
          "cur_vegetation_meth": "xxx",
          "experimental_factor": "xxx [ENVO:00000000]",
          "gaseous_environment": [
            "xxx"
          ],
          "microbial_biomass_C": "111 units",
          "microbial_biomass_N": "111 units",
          "tot_nitro_cont_meth": "xxx",
          "micro_biomass_C_meth": "xxx",
          "micro_biomass_N_meth": "xxx",
          "water_cont_soil_meth": "xxx",
          "experimental_factor_other": "xxx",
          "non_microb_biomass_method": "xxx"
        },
        {
          "elev": "123 m",
          "depth": "111-222",
          "lat_lon": "77 88",
          "ecosystem": "Environmental",
          "samp_name": "b",
          "env_medium": "bare soil [ENVO:01001616]",
          "store_cond": "frozen",
          "env_package": "soil",
          "sample_link": "z:99",
          "geo_loc_name": "USA: Maryland, Bethesda",
          "growth_facil": "greenhouse",
          "slope_aspect": "100 units",
          "analysis_type": [
            "metagenomics",
            "metatranscriptomics"
          ],
          "source_mat_id": "x:2",
          "ecosystem_type": "Soil",
          "collection_date": "2022-01-15",
          "env_broad_scale": "urban biome [ENVO:01000249]",
          "env_local_scale": "__tunnel [ENVO:00000068]",
          "samp_store_temp": "-80 Celsius",
          "ecosystem_subtype": "Unclassified",
          "ecosystem_category": "Terrestrial",
          "specific_ecosystem": "Unclassified"
        }
      ]
    }
  },
  "status": "in-progress",
  "id": "02a0cab2-3ff3-4663-a5e0-09a1a14a3f48",
  "author_orcid": "0000-0001-9076-6066",
  "created": "2023-03-15T22:05:46.138973",
  "author": {
    "id": "16e93541-3d1e-4cfd-825b-8b2de5a0b5b3",
    "orcid": "0000-0001-9076-6066",
    "name": "Mark Andrew Miller",
    "is_admin": true
  }
}
```

**Comment by turbomam** [comment]
Here's the sampleData extract, immediately after a very lazy conversion with https://www.json2yaml.com/

```yaml
---
sampleData:
  soil_data:
  - ph: '9'
    alt: 111 units
    elev: 123 m
    fire: xxx
    temp: 111 units
    depth: '111'
    lat_lon: 77 88
    ph_meth: xxx
    sieving: xxx
    tillage:
    - drill
    - chisel
    flooding: xxx
    salinity: 111 units
    tot_carb: 111 units
    ecosystem: Environmental
    fao_class: Rankers
    org_nitro: 111 units
    phosphate: 111 units
    samp_name: a
    samp_size: 111 units
    soil_type: xxx [ENVO:00000000]
    tot_phosp: 111 units
    env_medium: bare soil [ENVO:01001616]
    light_regm: ncandescant light;10 lux;450 nanometer
    org_matter: 111 units
    store_cond: frozen
    al_sat_meth: xxx
    annual_temp: 111 units
    biotic_regm: xxx
    env_package: soil
    local_class: xxx
    sample_link: z:99
    season_temp: 111 units
    cur_land_use: cities
    geo_loc_name: 'USA: Maryland, Bethesda'
    growth_facil: greenhouse
    horizon_meth: xxx
    size_frac_up: 111 units
    slope_aspect: 100 units
    soil_horizon: O horizon
    tot_org_carb: 111 units
    air_temp_regm:
    - xxx
    analysis_type:
    - metagenomics
    annual_precpt: 111 units
    crop_rotation: xxx
    extreme_event: xxx
    filter_method: xxx
    humidity_regm:
    - xxx
    oxy_stat_samp: aerobic
    rel_to_oxygen: aerobe
    salinity_meth: xxx
    season_precpt: 111 units
    size_frac_low: 99 units
    source_mat_id: x:1
    water_content: 111 units
    watering_regm:
    - xxx
    cur_vegetation: xxx
    drainage_class: well
    ecosystem_type: Soil
    slope_gradient: 111 units
    soil_type_meth: xxx
    start_date_inc: '2022-02-15'
    start_time_inc: '13:33:55'
    tot_org_c_meth: xxx
    collection_date: '2022-01-15'
    collection_time: '11:11'
    env_broad_scale: urban biome [ENVO:01000249]
    env_local_scale: __tunnel [ENVO:00000068]
    link_class_info: xxx
    other_treatment: xxx
    samp_store_temp: "-80 Celsius"
    carb_nitro_ratio: '0.5'
    isotope_exposure: xxx
    local_class_meth: xxx
    org_nitro_method: xxx
    profile_position: summit
    samp_mat_process: xxx
    ecosystem_subtype: Unclassified
    heavy_metals_meth: xxx
    link_climate_info: xxx
    microbial_biomass: 111 units
    previous_land_use: circus tent;+0530
    soil_text_measure: 111 units
    soil_texture_meth: xxx
    tot_nitro_content: 111 units
    ecosystem_category: Terrestrial
    micro_biomass_meth: xxx
    non_microb_biomass: 111 units
    prev_land_use_meth: xxx
    samp_collec_device: xxx
    samp_collec_method: xxx
    specific_ecosystem: Unclassified
    biotic_relationship: free living
    chem_administration:
    - xxx
    climate_environment:
    - xxx
    collection_date_inc: '2022-01-22'
    collection_time_inc: '11:11'
    cur_vegetation_meth: xxx
    experimental_factor: xxx [ENVO:00000000]
    gaseous_environment:
    - xxx
    microbial_biomass_C: 111 units
    microbial_biomass_N: 111 units
    tot_nitro_cont_meth: xxx
    micro_biomass_C_meth: xxx
    micro_biomass_N_meth: xxx
    water_cont_soil_meth: xxx
    experimental_factor_other: xxx
    non_microb_biomass_method: xxx
  - elev: 123 m
    depth: 111-222
    lat_lon: 77 88
    ecosystem: Environmental
    samp_name: b
    env_medium: bare soil [ENVO:01001616]
    store_cond: frozen
    env_package: soil
    sample_link: z:99
    geo_loc_name: 'USA: Maryland, Bethesda'
    growth_facil: greenhouse
    slope_aspect: 100 units
    analysis_type:
    - metagenomics
    - metatranscriptomics
    source_mat_id: x:2
    ecosystem_type: Soil
    collection_date: '2022-01-15'
    env_broad_scale: urban biome [ENVO:01000249]
    env_local_scale: __tunnel [ENVO:00000068]
    samp_store_temp: "-80 Celsius"
    ecosystem_subtype: Unclassified
    ecosystem_category: Terrestrial
    specific_ecosystem: Unclassified
```
