### ISSUE TITLE
This repo and nmdc-schema still have duped domain_of

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#71]
When looking at https://microbiomedata.github.io/submission-schema/AirInterface/#induced (for example)

```yaml
  air_PM_concen:
    ...
    domain_of:
    - Biosample
    - AirInterface
    - AirInterface 
```

This might be due to the fact that we're holding the linkml-runtime version back as the more recent versions don't merge schema files when creating a `SchemaView` from a URL.
