### ISSUE TITLE
Too much indentation for the EnvBroadScaleSoilEnum PVs etc

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#82]
```yaml
  EnvBroadScaleSoilEnum:
    name: EnvBroadScaleSoilEnum
    description: placeholder enum descr, DO NOT SORT
    from_schema: https://example.com/nmdc_submission_schema
    permissible_values:
      ________________mediterranean savanna biome [ENVO:01000229]:
        text: ________________mediterranean savanna biome [ENVO:01000229]
```
